const countries = {
    americas:[{"name":"Anguilla"},
                {"name":"Antigua and Barbuda"},
                {"name":"Argentina"},
                {"name":"Aruba"},
                {"name":"Bahamas"},
                {"name":"Barbados"},
                {"name":"Belize"},
                {"name":"Bermuda"},
                {"name":"Bolivia (Plurinational State of)"},
                {"name":"Bonaire Sint Eustatius and Saba"},
                {"name":"Brazil"},
                {"name":"United States Minor Outlying Islands"},
                {"name":"Virgin Islands (British)"},
                {"name":"Virgin Islands (U.S.)"},
                {"name":"Canada"},
                {"name":"Cayman Islands"},
                {"name":"Chile"},
                {"name":"Colombia"},
                {"name":"Costa Rica"},
                {"name":"Cuba"},
                {"name":"Curaçao"},
                {"name":"Dominica"},
                {"name":"Dominican Republic"},
                {"name":"Ecuador"},
                {"name":"El Salvador"},
                {"name":"Falkland Islands (Malvinas)"},
                {"name":"French Guiana"},
                {"name":"Greenland"},
                {"name":"Grenada"},
                {"name":"Guadeloupe"},
                {"name":"Guatemala"},
                {"name":"Guyana"},
                {"name":"Haiti"},
                {"name":"Honduras"},
                {"name":"Jamaica"},
                {"name":"Martinique"},
                {"name":"Mexico"},
                {"name":"Montserrat"},
                {"name":"Nicaragua"},
                {"name":"Panama"},
                {"name":"Paraguay"},
                {"name":"Peru"},
                {"name":"Puerto Rico"},
                {"name":"Saint Barthélemy"},
                {"name":"Saint Kitts and Nevis"},
                {"name":"Saint Lucia"},
                {"name":"Saint Martin (French part)"},
                {"name":"Saint Pierre and Miquelon"},
                {"name":"Saint Vincent and the Grenadines"},
                {"name":"Sint Maarten (Dutch part)"},
                {"name":"South Georgia and the South Sandwich Islands"},
                {"name":"Suriname"},
                {"name":"Trinidad and Tobago"},
                {"name":"Turks and Caicos Islands"},
                {"name":"United States of America"},
                {"name":"Uruguay"},
                {"name":"Venezuela (Bolivarian Republic of)"}],

    
    
    africa:[{"name":"Algeria"},
                {"name":"Angola"},
                {"name":"Benin"},
                {"name":"Botswana"},
                {"name":"British Indian Ocean Territory"},
                {"name":"Burkina Faso"},
                {"name":"Burundi"},
                {"name":"Cameroon"},
                {"name":"Cabo Verde"},
                {"name":"Central African Republic"},
                {"name":"Chad"},
                {"name":"Comoros"},
                {"name":"Congo"},
                {"name":"Congo (Democratic Republic of the)"},
                {"name":"Djibouti"},
                {"name":"Egypt"},
                {"name":"Equatorial Guinea"},
                {"name":"Eritrea"},
                {"name":"Ethiopia"},
                {"name":"French Southern Territories"},
                {"name":"Gabon"},
                {"name":"Gambia"},
                {"name":"Ghana"},
                {"name":"Guinea"},
                {"name":"Guinea-Bissau"},
                {"name":"Côte d'Ivoire"},
                {"name":"Kenya"},
                {"name":"Lesotho"},
                {"name":"Liberia"},
                {"name":"Libya"},
                {"name":"Madagascar"},
                {"name":"Malawi"},
                {"name":"Mali"},
                {"name":"Mauritania"},
                {"name":"Mauritius"},
                {"name":"Mayotte"},
                {"name":"Morocco"},
                {"name":"Mozambique"},
                {"name":"Namibia"},
                {"name":"Niger"},
                {"name":"Nigeria"},
                {"name":"Réunion"},
                {"name":"Rwanda"},
                {"name":"Saint Helena Ascension and Tristan da Cunha"},
                {"name":"Sao Tome and Principe"},
                {"name":"Senegal"},
                {"name":"Seychelles"},
                {"name":"Sierra Leone"},
                {"name":"Somalia"},
                {"name":"South Africa"},
                {"name":"South Sudan"},
                {"name":"Sudan"},
                {"name":"Swaziland"},
                {"name":"United Republic of Tanzania"},
                {"name":"Togo"},
                {"name":"Tunisia"},
                {"name":"Uganda"},
                {"name":"Western Sahara"},
                {"name":"Zambia"},
                {"name":"Zimbabwe"}],

    
    
    oceania:[{"name":"American Samoa"},
                 {"name":"Australia"},
                 {"name":"Christmas Island"},
                 {"name":"Cocos (Keeling) Islands"},
                 {"name":" Cook Islands"},
                 {"name":" Fiji"},
                 {"name":" French Polynesia"},
                 {"name":" Guam"},
                 {"name":" Kiribati"},
                 {"name":"Marshall Islands"},
                 {"name":"Micronesia (Federated States of)"},
                 {"name":"Nauru"},
                 {"name":"New Caledonia"},
                 {"name" :"New Zealand"},
                 {"name":"Niue"},
                 {"name":"Norfolk Island"},
                 {"name":"Northern Mariana Islands"},
                 {"name":"Palau"},
                 {"name":"Papua New Guinea"},
                {"name":"Pitcairn"},
                 {"name":"Samoa"},
                 {"name":"Solomon Islands"},
                 {"name":"Tokelau"},
                 {"name":"Tonga"}, 
                 {"name":"Tuvalu"},
                 {"name":"Vanuatu"},
                 {"name":"Wallis and Futuna"}],

    
    
    asia:[{"name":"Afghanistan"},
                 {"name":"Armenia"},
                 {"name":"Azerbaijan"},
                 {"name":"Bahrain"},
                 {"name":"Bangladesh"}, 
                 {"name":"Bhutan"},
                 {"name":"Brunei Darussalam"},
                 {"name":"Cambodia"},
                 {"name":"China"},
                 {"name":"Georgia" },
                 {"name":"Hong Kong"},
                 {"name":"India"},
                 {"name":"Indonesia"},
                 {"name":"Iran (Islamic Republic of)"},
                 {"name":" Iraq"},
                 {"name":" Israel"},
                 {"name":" Japan"},
                 {"name":" Jordan"},
                 {"name":" Kazakhstan"},
                 {"name":" Kuwait"},
                 {"name":" Kyrgyzstan"},
                 {"name":"Lao People's Democratic Republic"},
                 {"name":"Lebanon"},
                 {"name":"Macao"},
                 {"name":"Malaysia"},
                 {"name":"Maldives"},
                 {"name":" Mongolia"},
                 {"name":" Myanmar"},
                 {"name":" Nepal"},
                 {"name":"Democratic People's Republic of Korea"},
                 {"name":"Oman"},
                 {"name":"Pakistan"},
                 {"name":"State of Palestine"},
                 {"name":"Philippines"},
                 {"name":"Qatar" },
                 {"name":"Saudi Arabia"},
                 {"name":"Singapore"},
                 {"name":"Korea (Republic of)"},
                 {"name":"Sri Lanka"},
                 {"name":" Syrian Arab Republic"},
                 {"name":" Taiwan"},
                 {"name":" Tajikistan"},
                 {"name":" Thailand"},
                 {"name":" Timor-Leste"},
                 {"name":" Turkey"},
                 {"name":"Turkmenistan"},
                 {"name":"United Arab Emirates"},
                 {"name":"Uzbekistan"},
                 {"name":"Viet Nam"},
                 {"name":"Yemen"}],


    
    
    europe:[{"name":"Åland Islands"},
                {"name":"Albania"},
                {"name":"Andorra"},
                {"name":"Austria"},
                {"name":"Belarus"},
                {"name":"Belgium"},
                {"name":"Bosnia and Herzegovina"},
                {"name":"Bulgaria"},
                {"name":"Croatia"},
                {"name":"Cyprus"},
                {"name":"Czech Republic"},
                {"name":"Denmark"},
                {"name":"Estonia"},
                {"name":"Faroe Islands"},
                {"name":"Finland"},
                {"name":"France"},
                {"name":"Germany"},
                {"name":"Gibraltar"},
                {"name":"Greece"},
                {"name":"Guernsey"},
                {"name":"Holy See"},
                {"name":"Hungary"},
                {"name":"Iceland"},
                {"name":"Ireland"},
                {"name":"Isle of Man"},
                {"name":"Italy"},
                {"name":"Jersey"},
                {"name":"Latvia"},
                {"name":"Liechtenstein"},
                {"name":"Lithuania"},
                {"name":"Luxembourg"},
                {"name":"Macedonia (the former Yugoslav Republic of)"},
                {"name":"Malta"},
                {"name":"Moldova (Republic of)"},
                {"name":"Monaco"},
                {"name":"Montenegro"},
                {"name":"Netherlands"},
                {"name":"Norway"},
                {"name":"Poland"},
                {"name":"Portugal"},
                {"name":"Republic of Kosovo"},
                {"name":"Romania"},
                {"name":"Russian Federation"},
                {"name":"San Marino"},
                {"name":"Serbia"},
                {"name":"Slovakia"},
                {"name":"Slovenia"},
                {"name":"Spain"},
                {"name":"Svalbard and Jan Mayen"},
                {"name":"Sweden"},
                {"name":"Switzerland"},
                {"name":"Ukraine"},
                {"name":"United Kingdom of Great Britain and Northern Ireland"}]
}
export default countries